############# English navigation ##############

# main menu
[[main]]
weight = 1
url = "/"
name = "Home"
hasChildren = true

  [[main]]
  parent = "Home"
  weight = 1
  url = "homepage/list/"
  name = "List layout"

  [[main]]
  parent = "Home"
  weight = 2
  url = "homepage/grid/"
  name = "Grid layout"
  
[[main]]
weight = 3
url = "about/"
name = "About"

[[main]]
weight = 5
url = "#"
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  weight = 1
  url = "author/"
  name = "Author"
  
  [[main]]
  parent = "Pages"
  weight = 2
  url = "tags/"
  name = "Tags"
  
  [[main]]
  parent = "Pages"
  weight = 4
  url = "categories/"
  name = "Category"

############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "About"

