baseURL = "https://joone.github.io/"
languageCode = "en-us"
title = "Joone Blog"
theme="archie"
copyright = "© Joone Hur"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="bright"
	useCDN=false
	subtitle = "Web Browser, Free/Open Source, AI, and etc.."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/joone"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/joone/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
